title: Shawn Ong # your name (or website title) here
logo: "/images/WIN_20201221_16_35_43_Pro.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-driven person with high interest in technical skills and programming. 
  Excels through hands-on experience. 
  Huge interest in learnings, always open to pick up new skills and knowledge technical/data-related.  
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/shawnojk/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
